export const leadsTitle = [
    {
        field: 'id',
        headerName: 'ID',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'firstName',
        headerName: 'ИМЯ',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'lastName',
        headerName: 'ФАМИЛИЯ',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'username',
        headerName: 'USER',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'tgid',
        headerName: 'TG',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'status',
        headerName: 'СТАТУС',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'isFtd',
        headerName: 'isFTd',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'rdCount',
        headerName: 'rdCount',
        flex:1,
        disableColumnMenu: true,
    },
    {
        field: 'fbStatus',
        headerName: 'fbStatus',
        flex:1,
        disableColumnMenu: true,
    },
];

                    // "firstName": "LeadUserFirstName",
                    // "lastName": "LeadLastName",
                    // "phone": "123-456-7890",
                    // "username": "johndoe",
                    // "tgid": "tg12345",
                    // "subid": "sub12345",
                    // "status": "active",
                    // "isFtd": "true",
                    // "rdCount": "5",
                    // "fbStatus": "good",
                    // "sub1": "value1",
                    // "sub2": "value2",
                    // "sub3": "value3",
                    // "sub4": "value4",
                    // "sub5": "value5",
                    // "sub6": "value6",
                    // "sub7": "value7",
                    // "sub8": "value8",
                    // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"