export const projectsTitle = [
    {
        field: 'id',
        headerName: 'ID',
        disableColumnMenu: true,
        width: 80,
        // flex: 1,
        // maxWidth: 38,
    },
    {
        field: 'name',
        headerName: 'ПРОЕКТ',
        disableColumnMenu: true,
        minWidth: 170,
        // flex: 1,
        // maxWidth: 38,
    },
    {
        field: "leads",
        headerName: "Подписки",
        minWidth: 100,
        disableColumnMenu: true,
    },
    {
        field: "inactive",
        headerName: "Отписки",
        minWidth: 120,
        disableColumnMenu: true,
    },
    {
        field: "ftd",
        headerName: "FTD",
        width: 80,
        disableColumnMenu: true,
    },
    // {
    //     field: "ftdAmount",
    //     headerName: "Сумма FTD",
    //     minWidth: 120,
    //     disableColumnMenu: true,
    // },
    {
        field: "rd",
        headerName: "RD",
        width: 80,
        disableColumnMenu: true,
    },
    // {
    //     field: "rdAmount",
    //     headerName: "Сумма RD",
    //     minWidth: 120,
    //     disableColumnMenu: true,
    // },
    {
        field: "subsFtd",
        headerName: "Подп./FTD",
        minWidth: 170,
        disableColumnMenu: true,
    },
    {
        field: "ftdRd",
        headerName: "FTD/RD",
        minWidth: 120,
        disableColumnMenu: true,
    },
];