export const getProjectById = async (id,timeZone) => {
    //передаю айдішку проекта
    return {
        id: 1,
        name: 'Projects 1',
        subs: 3251,
        ftd: 10,
        rd: 10,
        buyerId: 'id1',
        pixelId: '123',
        leads: [
            {
                "firstName": "Lead1",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "rdAmount": '50',
                "regDate": '27.04.2024',
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "valuedsadsdasdasd3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead2",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "false",
                "rdCount": "5",
                "regDate": '27.04.2024',
                "fbStatus": "good",
                "ftdAmount": 20,
                "sub1": "value1",
                // "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead3",
                "lastName": "LeadLastNamasde",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "regDate": '27.02.2024',
                "subid": "sub12345",
                "status": "active",
                "isFtd": "false",
                "rdCount": "5",
                "fbStatus": "good",
                "sub1": "value2",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead4",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "regDate": '27.05.2024',
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead5",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "regDate": '27.02.2024',
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "inactive",
                "isFtd": "true",
                "rdCount": "100",
                "rdAmount": "50",
                "fbStatus": "bad",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead6",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "regDate": '16.05.2024',
                "subid": "sub12345",
                "status": "inactive",
                "isFtd": "true",
                "rdCount": "20",
                "fbStatus": "bad",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead7",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "regDate": '17.05.2024',
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead7",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "regDate": '18.05.2024',
                "isFtd": "true",
                "rdCount": "5",
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead7",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "regDate": '24.02.2024',
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead7",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "regDate": '28.01.2024',
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
            {
                "firstName": "Lead7",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "sub3": "value3",
                "sub4": "value4",
                "sub5": "value5",
                "regDate": '27.04.2023',
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            }, {
                "firstName": "Lead7",
                "lastName": "LeadLastName",
                "phone": "123-456-7890",
                "username": "johndoe",
                "tgid": "tg12345",
                "subid": "sub12345",
                "status": "active",
                "isFtd": "true",
                "rdCount": "5",
                "fbStatus": "good",
                "sub1": "value1",
                "sub2": "value2",
                "regDate": '27.01.2024',
                "sub4": "value4",
                "sub5": "value5",
                "sub6": "value6",
                "sub7": "value7",
                "sub8": "value8",
                // "projectId": "2cf7bc88-1098-4bf8-af92-420c75032c0f"
            },
        ]
    }
}